[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[runner]
magicEnabled = true

[theme]
primaryColor = "#3B82F6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9FB"
textColor = "#000000"
